Kentas_Website/KENTAS/KENTAS/KENTAS/Models/HumanResource.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KENTAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanResource
    {
        public int HumanResourceId { get; set; }
        public string HumanResourcePhoto { get; set; }
        public string HumanResourceTitle { get; set; }
        public string HumanResourceDescription { get; set; }
    }
}

Kentas_Website/KENTAS/KENTAS/KENTAS/Areas/Dashboard/Controllers/HumanResourceController.cs
using KENTAS.Models;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace KENTAS.Areas.Dashboard.Controllers
{
    [Authorize]
    public class HumanResourceController : Controller
    {
        Entities db = new Entities();
        // GET: Dashboard/HumanResource
        public ActionResult Index()
        {
            return View(db.HumanResources.ToList());
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Brand");
            }
            var humanResource = db.HumanResources.Where(x => x.HumanResourceId == id).SingleOrDefault();
            return View(humanResource);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "HumanResourceId,HumanResourcePhoto,HumanResourceTitle,HumanResourceDescription")] int id, HumanResource humanResource, HttpPostedFileBase HumanResourcePhoto)
        {
            if (ModelState.IsValid)
            {
                var b = db.HumanResources.Where(x => x.HumanResourceId == id).SingleOrDefault();
                if (HumanResourcePhoto != null)
                {

                    WebImage img = new WebImage(HumanResourcePhoto.InputStream);
                    FileInfo imginfo = new FileInfo(HumanResourcePhoto.FileName);
                    string humanResourcePhoto = Guid.NewGuid().ToString() + imginfo.Extension;
                    img.Save(Server.MapPath("~/Uploads/HumanResource/") + humanResourcePhoto);

                    b.HumanResourcePhoto = ("~/Uploads/HumanResource/" + humanResourcePhoto);
                }
                b.HumanResourceTitle = humanResource.HumanResourceTitle;
                b.HumanResourceDescription = humanResource.HumanResourceDescription;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(humanResource);
        }
    }
}

Kentas_Website/KENTAS/KENTAS/KENTAS/Areas/Dashboard/Views/HumanResource/Edit.cshtml
@model KENTAS.Models.HumanResource

@{
    ViewBag.Title = "Güncelle";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    CKEDITOR.replace('editor')
</script>

@using (Html.BeginForm("Edit", "HumanResource", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HumanResourceId)

        <div class="form-group">
            @Html.LabelFor(model => model.HumanResourcePhoto,"İNSAN KAYNAKLARI FOTOĞRAFI", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="HumanResourcePhoto" class="form-control" required placeholder="Dosya Seç." />
                @Html.ValidationMessageFor(model => model.HumanResourcePhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HumanResourceTitle,"İNSAN KAYNAKLARI BAŞLIK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HumanResourceTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HumanResourceTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HumanResourceDescription,"İNSAN KAYNAKLARI AÇIKLAMA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="HumanResourceDescription" class="ckeditor">@Model.HumanResourceDescription</textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Kentas_Website/KENTAS/KENTAS/KENTAS/Areas/Dashboard/Views/HumanResource/Index.cshtml
@model IEnumerable<KENTAS.Models.HumanResource>

@{
    ViewBag.Title = "İnsan Kaynakları";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";
}

<table class="table table-bordered table-striped table-responsive-sm">
    <tr>
        <th>
          İNSAN KAYNAKLARI FOTOĞRAFI
        </th>
        <th>
          İNSAN KAYNAKLARI BAŞLIK
        </th>
        <th>
          İNSAN KAYNAKLARI AÇIKLAMA
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src="@Url.Content(@item.HumanResourcePhoto)" alt="humanresource" style="width:200px; height:200px;" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HumanResourceTitle)
        </td>
        <td>
            @Html.Raw(item.HumanResourceDescription)
        </td>
        <td>
            @Html.ActionLink("Güncelle", "Edit", new { id = item.HumanResourceId }, new { @class = "btn btn-sm btn-success" })
        </td>
    </tr>
}

</table>