Kentas_Website/KENTAS/KENTAS/KENTAS/Areas/Dashboard/Controllers/ApplicationFormController.cs
using KENTAS.Models;
using System;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace KENTAS.Areas.Dashboard.Controllers
{
    [Authorize]
    public class ApplicationFormController : Controller
    {
        // GET: Dashboard/ApplicationForm
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> getForms()
        {
            using (Entities ct = new Entities())
            {
                var response = await ct.SubscriptionForms.ToListAsync();
                return Json(new { msg = "Başarılı", status = true, items = response }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public async Task<JsonResult> deleteForm(int request)
        {
            try
            {
                using (Entities ct = new Entities())
                {
                    var deleteService = await ct.SubscriptionForms.FirstOrDefaultAsync(f => f.ID == request);
                    if (deleteService != null)
                    {
                        ct.Entry(deleteService).State = EntityState.Deleted;
                        await ct.SaveChangesAsync();
                        return Json(new { msg = "Silme işlemi başarılı", status = true }, JsonRequestBehavior.AllowGet);

                    }
                    else
                        return Json(new { msg = "Hata: Hizmet bulunamadı", status = false }, JsonRequestBehavior.AllowGet);
                }

            }
            catch (Exception ex)
            {
                return Json(new { msg = "Hata: " + ex.Message, status = false }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Kentas_Website/KENTAS/KENTAS/KENTAS/Areas/Dashboard/Views/ApplicationForm/Index.cshtml
@{
    ViewBag.Title = "Başvuru Formları";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";
}


@section css{
    <style type="text/css">
        #map_canvas {
            height: 50vh;
        }


        @@media (max-width: 490px) {
            .e_close {
                display: none;
            }
        }
    </style>
}

<div style="width:100%; overflow-x:auto;">
    <table class="table table-bordered table-striped table-responsive-sm">
        <thead>
            <tr>
                <th class="e_close">T.C.</th>
                <th>AD SOYAD</th>
                <th>ARAÇ TİP</th>
                <th>PLAKA</th>
                <th>TEL</th>
                <th class="e_close">ADRES</th>
                <th>#</th>
            </tr>
        </thead>
        <tbody id="table-body">
        </tbody>
    </table>

</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Hizmet İşlemleri</h4>
            </div>
            <div class="modal-body">
                <form id="service-form">
                    <input type="hidden" value="0" name="Id" id="Id" />
                    <div class="form-group">
                        <label for="Title">Başlık</label>
                        <input type="text" class="form-control" id="Title" name="Title" placeholder="Hizmet adı" required />
                    </div>
                    <div class="form-inline">
                        <div class="form-group">
                            <label for="Sabahsaat">Sabah Çalışma Saati</label>
                            <input type="time" class="form-control" id="Sabahsaat" name="Sabahsaat" placeholder="Örnek: 08:30" required />
                        </div>
                        <div class="form-group">
                            <label for="Aksamsaat">Akşam Çalışma Saati</label>
                            <input type="time" class="form-control" id="Aksamsaat" name="Aksamsaat" placeholder="Örnek: 22:30" required />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Subtitile">Açıklama/Tanım</label>
                        <textarea rows="3" class="form-control" id="Subtitile" name="Subtitile" placeholder="Hizmet açıklaması" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="Adress">Adres</label>
                        <textarea rows="3" class="form-control" id="Adress" name="Adress" placeholder="Adres" required></textarea>
                    </div>

                    <div class="form-inline mb-3">
                        <div class="form-group">
                            <label for="Lat">Kordinat</label>
                            <input type="text" class="form-control" id="Lat" name="Lat" placeholder="41.00" required />
                        </div>
                        <div class="form-group">
                            <label for="Lng">&nbsp;</label>
                            <input type="text" class="form-control" id="Lng" name="Lng" placeholder="-41.00" required />
                        </div>
                    </div>

                    <div style="margin-top:15px;" id="map_canvas"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Vazgeç</button>
                <button type="button" class="btn btn-primary" onclick="saveService()">Kaydet <i class="fa fa-save"></i></button>
            </div>
        </div>
    </div>
</div>

@section scripts {
   
    <script type="text/javascript">
        var l = 39.7667061;
        var n = 30.5256311;
        $(() => {
            $($('[href="' + location.pathname + '"]')[0].parentElement).addClass('active');

            getForms();
        })

        var getForms = () => {
            $('#table-body').empty();
            $.getJSON('@Url.Action("getForms", "ApplicationForm")', (d, s) => {
                if (s === "success") {
                    for (let item of d.items) {
                        let str = `<tr id="row_${item.ID}">
                                    <td class="e_close">${item.TcKimlikNo}</td>
                                    <td >${item.Ad} ${item.Soyad}</td>
                                    <td>${item.AracTipi}</td>
                                    <td>${item.Plaka}</td>
                                    <td>${item.CepTel}</td>
                                    <td class="e_close">${item.Adres}</td>
                                    <td>
                                         <a href="javascript:deleteForm(${item.ID});" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                                    </td>
                                   </tr>`;
                        $('#table-body').append(str);
                    }
                }
            });
        }

        var deleteForm = (sId) => {
            var r = confirm("Seçili Kayıt silinsinmi ?");
            if (r == true) {
                $.get('@Url.Action("deleteForm", "ApplicationForm")', { request : sId}, (d, s) => {

                    if (s === "success") {
                        if (d.status) {
                            $('#row_' + sId).fadeOut();
                        }
                        alert(d.msg);
                    }

                })

            }
        }

    </script>
}